import requests
import os
import random
import sys
from datetime import datetime

# ---------------- CONFIGURATION ---------------- #
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")

# ---------------- AUTO TOPIC GENERATION ---------------- #
def generate_new_topics_from_gemini(count=20):
    """Gemini ကို ခေါ်ပြီး ခေတ်စားနေတဲ့ Topic အသစ်တွေ ထုတ်ယူမယ်"""
    prompt = f"""Generate {count} engaging phone shop related topics for a Myanmar Facebook page.

Each topic should be:
- Written in Myanmar language
- Useful for phone shop customers (tips, news, comparisons, how-to)
- Engaging and clickable
- Under 15 words each

Categories to include:
- Phone buying tips
- New phone models
- Battery care
- Phone comparison
- Hidden features
- Problem solving
- Latest tech news

Return ONLY the topics, one per line, no numbering, no extra text.

Example format:
ဖုန်းအသစ်ဝယ်မယ်ဆို သိထားသင့်တဲ့အချက် ၅ ချက်
ဖုန်းအားသွင်းတဲ့အခါ သတိထားရမယ့်အချက်များ
"""

    try:
        response_text = generate_gemini_text(prompt)
        
        # တစ်ကြောင်းချင်းစီ ခွဲပြီး clean လုပ်မယ်
        topics = []
        for line in response_text.strip().split('\n'):
            line = line.strip()
            # နံပါတ်စဉ်တွေ၊ စာလုံးတွေ ဖယ်ရှားမယ်
            if line and not line.startswith('#') and len(line) > 5:
                # နံပါတ်စဉ်တွေ (1. 2. - etc) ဖယ်ရှားမယ်
                if line[0].isdigit() and '. ' in line[:3]:
                    line = line.split('. ', 1)[1]
                elif line[0] in '-•*':
                    line = line[1:].strip()
                topics.append(line)
        
        return topics[:count]
    except Exception as e:
        print(f"Topic generation error: {e}")
        return None

def auto_refresh_topics():
    """topics.txt ကို Gemini ကနေ Topic အသစ်တွေနဲ့ အစားထိုးမယ်"""
    print("🔄 Auto refreshing topics from Gemini...")
    
    new_topics = generate_new_topics_from_gemini(30)
    
    if new_topics and len(new_topics) > 5:
        save_topics(new_topics)
        print(f"✅ Topics refreshed! {len(new_topics)} new topics saved.")
        
        # Telegram ကို အကြောင်းကြားမယ် (optional)
        message = f"🔄 **Topic List Updated!**\n\n📚 New topics generated by Gemini: {len(new_topics)} topics\n\n示例 topics:\n"
        for topic in new_topics[:5]:
            message += f"• {topic}\n"
        send_message_to_telegram(message)
        
        return True
    else:
        print("❌ Failed to generate new topics")
        return False

# ---------------- TOPICS FILE FUNCTIONS ---------------- #
def load_topics():
    """topics.txt ဖိုင်ကနေ Topic စာရင်းကို ဖတ်မယ်"""
    if os.path.exists("topics.txt"):
        with open("topics.txt", "r", encoding="utf-8") as f:
            topics = [line.strip() for line in f if line.strip()]
            if topics:
                return topics
    
    # topics.txt မရှိရင် Gemini ကနေ အလိုအလျောက် ထုတ်ယူမယ်
    print("📭 topics.txt not found. Generating from Gemini...")
    new_topics = generate_new_topics_from_gemini(20)
    if new_topics:
        save_topics(new_topics)
        return new_topics
    
    # Gemini မရရင် default topics သုံးမယ်
    return [
        "ဖုန်းအသစ်ဝယ်မယ်ဆို သိထားသင့်တဲ့အချက် ၅ ချက်",
        "ဖုန်းအားသွင်းတဲ့အခါ သတိထားရမယ့်အချက်များ",
        "Redmi Note 14 Pro ရဲ့ အားသာချက်များ",
    ]

def save_topics(topics):
    """Topic စာရင်းကို topics.txt မှာ သိမ်းမယ်"""
    with open("topics.txt", "w", encoding="utf-8") as f:
        for topic in topics:
            f.write(topic + "\n")

def add_topic(topic):
    """Topic အသစ်ထည့်မယ်"""
    topics = load_topics()
    if topic in topics:
        return False, "❌ ဒီ Topic ရှိပြီးသားပါ။"
    topics.append(topic)
    save_topics(topics)
    return True, f"✅ Topic အသစ်ထည့်ပြီးပါပြီ။\n\n📌 {topic}"

def remove_topic(index):
    """နံပါတ်အလိုက် Topic ဖျက်မယ်"""
    topics = load_topics()
    if 1 <= index <= len(topics):
        removed = topics.pop(index - 1)
        save_topics(topics)
        return True, f"✅ ဖျက်ပြီးပါပြီ။\n\n❌ {removed}"
    return False, f"❌ နံပါတ် {index} က မရှိပါ။ (၁ မှ {len(topics)} အတွင်းထည့်ပါ)"

def get_topics_list_text():
    """Topic စာရင်းကို လှလှပပ format လုပ်မယ်"""
    topics = load_topics()
    if not topics:
        return "📭 topics.txt ထဲမှာ Topic မရှိသေးပါ။"
    
    text = f"📚 **Topic List** (စုစုပေါင်း {len(topics)} ခု)\n\n"
    for i, topic in enumerate(topics[:20]):  # အများဆုံး 20 ခုပြမယ်
        text += f"{i+1}. {topic}\n"
    
    if len(topics) > 20:
        text += f"\n...နှင့် နောက်ထပ် {len(topics)-20} ခု"
    
    return text

# ---------------- GEMINI FUNCTION ---------------- #
def generate_gemini_text(prompt):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key={GEMINI_API_KEY}"
    
    headers = {"Content-Type": "application/json"}
    data = {
        "contents": [{
            "parts": [{"text": prompt}]
        }]
    }
    
    response = requests.post(url, headers=headers, json=data, timeout=60)
    
    if response.status_code == 200:
        result = response.json()
        return result["candidates"][0]["content"]["parts"][0]["text"]
    else:
        raise Exception(f"Gemini API Error: {response.text}")

# ---------------- CONTENT GENERATOR ---------------- #
def generate_facebook_post(topic):
    prompt = f"""Write a Facebook post about "{topic}" in Myanmar language.

Write like a friendly phone shop owner talking to customers.

Structure:
1. HOOK - Eye-catching first line with emojis
2. CONTENT - 3-5 key points with ✅ emojis as bullet points
3. CTA - Call to action (ask a question to engage readers)
4. HASHTAGS - 3 hashtags like #PhoneTips #MyanmarTech

Keep under 1000 characters. Use natural, conversational Myanmar language.
Do NOT include any English intro like "Here is a post about...".
"""

    return generate_gemini_text(prompt)

# ---------------- TELEGRAM FUNCTIONS ---------------- #
def send_message_to_telegram(text, chat_id=None):
    if chat_id is None:
        chat_id = TELEGRAM_CHAT_ID
    
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": text[:4000],
        "parse_mode": "Markdown"
    }
    response = requests.post(url, json=payload, timeout=60)
    
    if response.status_code != 200:
        print(f"Telegram Error: {response.text}")
    return response.status_code == 200

# ---------------- AUTO MODE (GitHub Actions ခေါ်မယ်) ---------------- #
def run_auto_post():
    """GitHub Actions က ဒီ function ကို နာရီတိုင်း ခေါ်မယ်"""
    print("🚀 Auto Post Started at", datetime.now())
    
    topics = load_topics()
    if not topics:
        print("❌ No topics found")
        return
    
    topic = random.choice(topics)
    print(f"📌 Selected Topic: {topic}")
    
    print("✍️ Generating content with Gemini...")
    content = generate_facebook_post(topic)
    
    print("📤 Sending to Telegram...")
    send_message_to_telegram(content)
    
    print("✅ All done!")

def run_auto_refresh_topics():
    """Topic List ကို Gemini နဲ့ အသစ်ပြောင်းမယ် (နေ့စဉ် တစ်ခါခေါ်)"""
    print("🔄 Running auto topic refresh at", datetime.now())
    auto_refresh_topics()

# ---------------- MAIN ---------------- #
if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1] == "auto":
            run_auto_post()
        elif sys.argv[1] == "refresh":
            run_auto_refresh_topics()
        elif sys.argv[1] == "bot":
            # Bot polling mode အတွက် (local server မှာ run ချင်ရင်)
            from telegram.ext import Application, CommandHandler
            
            async def handle_command(update, context):
                chat_id = update.effective_chat.id
                command = update.message.text.lower()
                
                if command == "/view_topics":
                    text = get_topics_list_text()
                    await update.message.reply_text(text)
                elif command == "/add_topic":
                    args = update.message.text.replace("/add_topic", "").strip()
                    if not args:
                        await update.message.reply_text("❌ Topic အမည်ထည့်ပေးပါ။")
                        return
                    success, message = add_topic(args)
                    await update.message.reply_text(message)
                elif command == "/remove_topic":
                    args = update.message.text.replace("/remove_topic", "").strip()
                    if not args or not args.isdigit():
                        await update.message.reply_text("❌ နံပါတ်ထည့်ပေးပါ။")
                        return
                    success, message = remove_topic(int(args))
                    await update.message.reply_text(message)
                elif command == "/random_post":
                    topics = load_topics()
                    if not topics:
                        await update.message.reply_text("❌ topics.txt ထဲမှာ Topic မရှိပါ။")
                        return
                    topic = random.choice(topics)
                    await update.message.reply_text(f"🎲 Random Topic: {topic}\n\n⏳ Post တင်နေပါပြီ...")
                    content = generate_facebook_post(topic)
                    send_message_to_telegram(content)
                    await update.message.reply_text("✅ Post တင်ပြီးပါပြီ။")
                elif command == "/refresh_topics":
                    await update.message.reply_text("🔄 Topic list အသစ်ပြောင်းနေပါပြီ... ခဏစောင့်ပါ။")
                    success = auto_refresh_topics()
                    if success:
                        await update.message.reply_text("✅ Topic list ကို အသစ်ပြောင်းပြီးပါပြီ။ `/view_topics` နဲ့ ကြည့်ပါ။")
                    else:
                        await update.message.reply_text("❌ Topic list အသစ်ပြောင်းရာမှာ အဆင်မပြေပါ။")
                elif command == "/help":
                    help_text = """
🤖 **Phone Shop Bot Commands**

📋 **Topic Management:**
• `/view_topics` - Topic စာရင်းကြည့်ရန်
• `/add_topic [topic]` - Topic အသစ်ထည့်ရန်
• `/remove_topic [နံပါတ်]` - Topic ဖျက်ရန်
• `/refresh_topics` - Gemini နဲ့ Topic အသစ်တွေ ထုတ်ယူမည်

📝 **Post:**
• `/random_post` - Random Topic ရွေးပြီး Post တင်ရန်

⏰ **Auto Post:**
• မနက် ၈:၀၀ မှ ည ၈:၀၀ အထိ တစ်နာရီတစ်ခါ
"""
                    await update.message.reply_text(help_text)
            
            app = Application.builder().token(TELEGRAM_BOT_TOKEN).build()
            app.add_handler(CommandHandler("view_topics", handle_command))
            app.add_handler(CommandHandler("add_topic", handle_command))
            app.add_handler(CommandHandler("remove_topic", handle_command))
            app.add_handler(CommandHandler("random_post", handle_command))
            app.add_handler(CommandHandler("refresh_topics", handle_command))
            app.add_handler(CommandHandler("help", handle_command))
            app.add_handler(CommandHandler("start", handle_command))
            
            print("🤖 Bot is running...")
            app.run_polling()
    else:
        print("Usage:")
        print("  python main.py auto          # Run auto post once")
        print("  python main.py refresh       # Refresh topics from Gemini")
        print("  python main.py bot           # Run bot with commands")
